spring:
  application.name: devices-configuration
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 15
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:db/db.changelog.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    security:
      protocol: SASL_SSL
    properties:
      ssl.endpoint.identification.algorithm: https
    jaas:
      enabled: true
      control-flag: required
      login-module: org.apache.kafka.common.security.scram.ScramLoginModule
      options:
        username: ${KAFKA_JAAS_USERNAME}
        password: ${KAFKA_JAAS_PASSWORD}
    consumer:
      group-id: devices-configuration-default
      auto-offset-reset: earliest
      ssl:
        trust-store-location: ${KAFKA_SSL_TRUST_STORE_LOCATION}
        trust-store-password: ${KAFKA_SSL_TRUST_STORE_PASSWORD}
      properties:
        sasl.mechanism: SCRAM-SHA-512
    producer:
      ssl:
        trust-store-location: ${KAFKA_SSL_TRUST_STORE_LOCATION}
        trust-store-password: ${KAFKA_SSL_TRUST_STORE_PASSWORD}
      properties:
        sasl.mechanism: SCRAM-SHA-512
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://keycloak.auth/realms/iot"
server:
  shutdown: graceful
  error:
    include-message: never

management:
  metrics.export.prometheus.enabled: true
  endpoint.env.enabled: true
  endpoints.web.exposure.include: "health,info,env,prometheus"

logging.level:
  org.apache.catalina.startup.DigesterFactory: ERROR
  org.apache.catalina.util.LifecycleBase: ERROR
  org.apache.coyote.http11.Http11NioProtocol: WARN
  org.apache.sshd.common.util.SecurityUtils: WARN
  org.apache.tomcat.util.net.NioSelectorPool: WARN
  org.eclipse.jetty.util.component.AbstractLifeCycle: ERROR
  org.hibernate.validator.internal.util.Version: WARN
  org.springframework.boot.actuate.endpoint.jmx: WARN
  org.springframework.web: INFO
  org.apache.kafka: WARN
  org.apache.kafka.clients.consumer.ConsumerConfig: INFO
  org.apache.kafka.clients.producer.ProducerConfig: INFO
  org.apache.kafka.clients.admin.AdminClientConfig: INFO
  org.apache.kafka.common.utils.AppInfoParser: INFO
  org.apache.kafka.streams.StreamsConfig: INFO
